### ISSUE TITLE
SyntaxError: Unexpected token ;

### ISSUE THREAD

**Issue by dbkaplun** [genomejs/genoset-norovirus#1]
``` js
> require('genoset-norovirus')(dna);
/Users/dan/node_modules/genoset-norovirus/index.js:6
    immune: test(data);
                      ^
SyntaxError: Unexpected token ;
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
```

**Comment by dbkaplun** [comment]
Confirmed! :)
